// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 14.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace PortableHotspotWindows.CodedUI
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UITesting.WpfControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public partial class UIMap
    {
        
        /// <summary>
        /// StartStopAboutAndExit
        /// </summary>
        public void StartStopAboutAndExit()
        {
            #region Variable Declarations
            WinTitleBar uIPortableHotspotWindoTitleBar = this.UIPortableHotspotWindoWindow.UIPortableHotspotWindoTitleBar;
            WinButton uIStartHotspotButton = this.UIPortableHotspotWindoWindow.UIStartHotspotWindow.UIStartHotspotButton;
            WinButton uIShowPassButtonButton = this.UIPortableHotspotWindoWindow.UIShowPassButtonWindow.UIShowPassButtonButton;
            WinButton uIStopHostspotButton = this.UIPortableHotspotWindoWindow.UIStartHotspotWindow.UIStopHostspotButton;
            WinMenuItem uIAboutMenuItem = this.UIPortableHotspotWindoWindow.UIMainMenuStripMenuMenuBar.UIAboutMenuItem;
            WinButton uICloseButton = this.UIAboutWindow.UICloseWindow.UICloseButton;
            WinMenuItem uIExitMenuItem = this.UIPortableHotspotWindoWindow.UIMainMenuStripMenuMenuBar.UIExitMenuItem;
            WinButton uIYesButton = this.UIInformationWindow.UIYesWindow.UIYesButton;
            #endregion

            // Click 'Portable Hotspot Windows' title bar
            Mouse.Click(uIPortableHotspotWindoTitleBar, new Point(157, 6));

            // Click 'Start Hotspot' button
            Mouse.Click(uIStartHotspotButton, new Point(72, 40));

            // Click 'ShowPassButton' button
            Mouse.Click(uIShowPassButtonButton, new Point(19, 17));

            // Click 'Stop Hostspot' button
            Mouse.Click(uIStopHostspotButton, new Point(82, 32));

            // Click 'About' menu item
            Mouse.Click(uIAboutMenuItem, new Point(29, 5));

            // Click 'Close' button
            Mouse.Click(uICloseButton, new Point(37, 11));

            // Click 'Exit' menu item
            Mouse.Click(uIExitMenuItem, new Point(13, 2));

            // Click '&Yes' button
            Mouse.Click(uIYesButton, new Point(61, 20));
        }
        
        /// <summary>
        /// SetNetworkShareInternetMinimize - Use 'SetNetworkShareInternetMinimizeParams' to pass parameters into this method.
        /// </summary>
        public void SetNetworkShareInternetMinimize()
        {
            #region Variable Declarations
            WinTitleBar uIPortableHotspotWindoTitleBar = this.UIPortableHotspotWindoWindow.UIPortableHotspotWindoTitleBar;
            WinMenuItem uISetNetworkMenuItem = this.UIPortableHotspotWindoWindow.UIMainMenuStripMenuMenuBar.UISetNetworkMenuItem;
            WinEdit uISSIDTextBoxEdit = this.UISetHotspotWindow.UISSIDTextBoxWindow.UISSIDTextBoxEdit;
            WinEdit uIKeyTextBoxEdit = this.UISetHotspotWindow.UIKeyTextBoxWindow.UIKeyTextBoxEdit;
            WinButton uITOButton = this.UISetHotspotWindow.UIShowPassButtonWindow.UITOButton;
            WinButton uISetButton = this.UISetHotspotWindow.UISetWindow.UISetButton;
            WinButton uIOpenButton = this.UISetHotspotWindow.UIFromNetworkListComboWindow.UIOpenButton;
            WinComboBox uIFromNetworkListComboComboBox = this.UISetHotspotWindow.UIFromNetworkListComboWindow.UIFromNetworkListComboComboBox;
            WinButton uIOpenButton1 = this.UISetHotspotWindow.UIToNetworkListComboBoWindow.UIOpenButton;
            WinComboBox uIToNetworkListComboBoComboBox = this.UISetHotspotWindow.UIToNetworkListComboBoWindow.UIToNetworkListComboBoComboBox;
            WinButton uIShareInternetButton = this.UISetHotspotWindow.UIShareInternetWindow.UIShareInternetButton;
            WinButton uICloseButton = this.UISetHotspotWindow.UISetHotspotTitleBar.UICloseButton;
            WinButton uIShowPassButtonButton = this.UIPortableHotspotWindoWindow.UIShowPassButtonWindow.UIShowPassButtonButton;
            WinButton uIStartHotspotButton = this.UIPortableHotspotWindoWindow.UIStartHotspotWindow.UIStartHotspotButton;
            WinButton uIStopHostspotButton = this.UIPortableHotspotWindoWindow.UIStartHotspotWindow.UIStopHostspotButton;
            WinButton uIMinimizeButton = this.UIPortableHotspotWindoWindow.UIPortableHotspotWindoTitleBar.UIMinimizeButton;
            WinButton uIPortableHotspotWindoButton = this.UIUserPromotedNotificaWindow.UIUserPromotedNotificaToolBar.UIPortableHotspotWindoButton;
            HtmlDiv uIItemPane = this.UIPortableHotspotWindoWindow2.UIDiagnosticToolsPane.UIItemPane.UISystemResourceNotifyClient.UIDiagnosticToolsWindow.UIItemCustom.UIDiagnosticToolsCustom.UIItemPane.UIItemClient.UISwimlanesViewDocument.UIMainSwimlaneContainePane.UIItemPane;
            HtmlCustom uIItemCustom = this.UIPortableHotspotWindoWindow2.UIDiagnosticToolsPane.UIItemPane.UISystemResourceNotifyClient.UIDiagnosticToolsWindow.UIItemCustom.UIDiagnosticToolsCustom.UIItemPane.UIItemClient.UISwimlanesViewDocument.UIMainSwimlaneContainePane.UIItemCustom;
            HtmlCustom uIItemCustom1 = this.UIPortableHotspotWindoWindow2.UIDiagnosticToolsPane.UIItemPane.UISystemResourceNotifyClient.UIDiagnosticToolsWindow.UIItemCustom.UIDiagnosticToolsCustom.UIItemPane.UIItemClient.UISwimlanesViewDocument.UIMainSwimlaneContainePane.UIItemCustom1;
            HtmlDiv uIItemPane1 = this.UIPortableHotspotWindoWindow2.UIDiagnosticToolsPane.UIItemPane.UISystemResourceNotifyClient.UIDiagnosticToolsWindow.UIItemCustom.UIDiagnosticToolsCustom.UIItemPane.UIItemClient.UISwimlanesViewDocument.UIFooterPane.UIItemPane;
            WinButton uIStopHostspotButton1 = this.UIPortableHotspotWindoWindow.UIStopHostspotWindow.UIStopHostspotButton;
            WinButton uICloseButton1 = this.UIPortableHotspotWindoWindow.UIPortableHotspotWindoTitleBar.UICloseButton;
            WinButton uIYesButton = this.UIInformationWindow.UIYesWindow.UIYesButton;
            #endregion

            // Click 'Portable Hotspot Windows' title bar
            Mouse.Click(uIPortableHotspotWindoTitleBar, new Point(127, 15));

            // Click 'Set Network' menu item
            Mouse.Click(uISetNetworkMenuItem, new Point(39, 10));

            // Type 'Samsung' in 'SSIDTextBox' text box
            uISSIDTextBoxEdit.Text = this.SetNetworkShareInternetMinimizeParams.UISSIDTextBoxEditText;

            // Click 'KeyTextBox' text box
            Mouse.Click(uIKeyTextBoxEdit, new Point(97, 1));

            // Type '********' in 'KeyTextBox' text box
            Keyboard.SendKeys(uIKeyTextBoxEdit, this.SetNetworkShareInternetMinimizeParams.UIKeyTextBoxEditSendKeys, true);

            // Click 'To' button
            Mouse.Click(uITOButton, new Point(26, 7));

            // Click 'Set' button
            Mouse.Click(uISetButton, new Point(35, 25));

            // Click 'Open' button
            Mouse.Click(uIOpenButton, new Point(5, 12));

            // Select 'Ethernet' in 'FromNetworkListComboBox' combo box
            uIFromNetworkListComboComboBox.SelectedItem = this.SetNetworkShareInternetMinimizeParams.UIFromNetworkListComboComboBoxSelectedItem;

            // Click 'Open' button
            Mouse.Click(uIOpenButton1, new Point(7, 9));

            // Select 'Local Area Connection* 3' in 'ToNetworkListComboBox' combo box
            uIToNetworkListComboBoComboBox.SelectedItem = this.SetNetworkShareInternetMinimizeParams.UIToNetworkListComboBoComboBoxSelectedItem;

            // Click 'Share Internet' button
            Mouse.Click(uIShareInternetButton, new Point(35, 15));

            // Click 'Share Internet' button
            Mouse.Click(uIShareInternetButton, new Point(33, 17));

            // Click 'Close' button
            Mouse.Click(uICloseButton, new Point(19, 18));

            // Click 'ShowPassButton' button
            Mouse.Click(uIShowPassButtonButton, new Point(8, 13));

            // Click 'Start Hotspot' button
            Mouse.Click(uIStartHotspotButton, new Point(104, 39));

            // Click 'Stop Hostspot' button
            Mouse.Click(uIStopHostspotButton, new Point(90, 34));

            // Click 'Minimize' button
            Mouse.Click(uIMinimizeButton, new Point(18, 16));

            // Double-Click 'Portable Hotspot Windows' button
            Mouse.DoubleClick(uIPortableHotspotWindoButton, new Point(17, 18));

            // Click 'Start Hotspot' button
            Mouse.Click(uIStartHotspotButton, new Point(86, 34));

            // Click 'Minimize' button
            Mouse.Click(uIMinimizeButton, new Point(24, 10));

            // Set flag to allow play back to continue if non-essential actions fail. (For example, if a mouse hover action fails.)
            Playback.PlaybackSettings.ContinueOnError = true;

            // Mouse hover  pane at (1, 1)
            Mouse.Hover(uIItemPane, new Point(1, 1));

            // Mouse hover  custom control at (1, 1)
            Mouse.Hover(uIItemCustom, new Point(1, 1));

            // Mouse hover  custom control at (1, 1)
            Mouse.Hover(uIItemCustom1, new Point(1, 1));

            // Mouse hover  pane at (1, 1)
            Mouse.Hover(uIItemPane1, new Point(1, 1));

            // Reset flag to ensure that play back stops if there is an error.
            Playback.PlaybackSettings.ContinueOnError = false;

            // Double-Click 'Portable Hotspot Windows' button
            Mouse.DoubleClick(uIPortableHotspotWindoButton, new Point(13, 22));

            // Click 'Stop Hostspot' button
            Mouse.Click(uIStopHostspotButton1, new Point(120, 37));

            // Click 'Close' button
            Mouse.Click(uICloseButton1, new Point(20, 17));

            // Click '&Yes' button
            Mouse.Click(uIYesButton, new Point(33, 21));
        }
        
        #region Properties
        public virtual SetNetworkShareInternetMinimizeParams SetNetworkShareInternetMinimizeParams
        {
            get
            {
                if ((this.mSetNetworkShareInternetMinimizeParams == null))
                {
                    this.mSetNetworkShareInternetMinimizeParams = new SetNetworkShareInternetMinimizeParams();
                }
                return this.mSetNetworkShareInternetMinimizeParams;
            }
        }
        
        public UIPortableHotspotWindoWindow UIPortableHotspotWindoWindow
        {
            get
            {
                if ((this.mUIPortableHotspotWindoWindow == null))
                {
                    this.mUIPortableHotspotWindoWindow = new UIPortableHotspotWindoWindow();
                }
                return this.mUIPortableHotspotWindoWindow;
            }
        }
        
        public UIAboutWindow UIAboutWindow
        {
            get
            {
                if ((this.mUIAboutWindow == null))
                {
                    this.mUIAboutWindow = new UIAboutWindow();
                }
                return this.mUIAboutWindow;
            }
        }
        
        public UIInformationWindow UIInformationWindow
        {
            get
            {
                if ((this.mUIInformationWindow == null))
                {
                    this.mUIInformationWindow = new UIInformationWindow();
                }
                return this.mUIInformationWindow;
            }
        }
        
        public UISetHotspotWindow UISetHotspotWindow
        {
            get
            {
                if ((this.mUISetHotspotWindow == null))
                {
                    this.mUISetHotspotWindow = new UISetHotspotWindow();
                }
                return this.mUISetHotspotWindow;
            }
        }
        
        public UIUserPromotedNotificaWindow UIUserPromotedNotificaWindow
        {
            get
            {
                if ((this.mUIUserPromotedNotificaWindow == null))
                {
                    this.mUIUserPromotedNotificaWindow = new UIUserPromotedNotificaWindow();
                }
                return this.mUIUserPromotedNotificaWindow;
            }
        }
        
        public UIPortableHotspotWindoWindow2 UIPortableHotspotWindoWindow2
        {
            get
            {
                if ((this.mUIPortableHotspotWindoWindow2 == null))
                {
                    this.mUIPortableHotspotWindoWindow2 = new UIPortableHotspotWindoWindow2();
                }
                return this.mUIPortableHotspotWindoWindow2;
            }
        }
        #endregion
        
        #region Fields
        private SetNetworkShareInternetMinimizeParams mSetNetworkShareInternetMinimizeParams;
        
        private UIPortableHotspotWindoWindow mUIPortableHotspotWindoWindow;
        
        private UIAboutWindow mUIAboutWindow;
        
        private UIInformationWindow mUIInformationWindow;
        
        private UISetHotspotWindow mUISetHotspotWindow;
        
        private UIUserPromotedNotificaWindow mUIUserPromotedNotificaWindow;
        
        private UIPortableHotspotWindoWindow2 mUIPortableHotspotWindoWindow2;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'SetNetworkShareInternetMinimize'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class SetNetworkShareInternetMinimizeParams
    {
        
        #region Fields
        /// <summary>
        /// Type 'Samsung' in 'SSIDTextBox' text box
        /// </summary>
        public string UISSIDTextBoxEditText = "Samsung";
        
        /// <summary>
        /// Type '********' in 'KeyTextBox' text box
        /// </summary>
        public string UIKeyTextBoxEditSendKeys = "euX4sCJh368ZqJJ3VFBGEQij0rqbhb8gcMgBUbIlCRgoZoCM3Zp7NGqdYfZBYsscM9GZH78TS+WIzi07d" +
            "ewyWXLGebMuwntW";
        
        /// <summary>
        /// Select 'Ethernet' in 'FromNetworkListComboBox' combo box
        /// </summary>
        public string UIFromNetworkListComboComboBoxSelectedItem = "Ethernet";
        
        /// <summary>
        /// Select 'Local Area Connection* 3' in 'ToNetworkListComboBox' combo box
        /// </summary>
        public string UIToNetworkListComboBoComboBoxSelectedItem = "Local Area Connection* 3";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIPortableHotspotWindoWindow : WinWindow
    {
        
        public UIPortableHotspotWindoWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Portable Hotspot Windows";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Portable Hotspot Windows");
            #endregion
        }
        
        #region Properties
        public UIPortableHotspotWindoTitleBar UIPortableHotspotWindoTitleBar
        {
            get
            {
                if ((this.mUIPortableHotspotWindoTitleBar == null))
                {
                    this.mUIPortableHotspotWindoTitleBar = new UIPortableHotspotWindoTitleBar(this);
                }
                return this.mUIPortableHotspotWindoTitleBar;
            }
        }
        
        public UIStartHotspotWindow UIStartHotspotWindow
        {
            get
            {
                if ((this.mUIStartHotspotWindow == null))
                {
                    this.mUIStartHotspotWindow = new UIStartHotspotWindow(this);
                }
                return this.mUIStartHotspotWindow;
            }
        }
        
        public UIShowPassButtonWindow UIShowPassButtonWindow
        {
            get
            {
                if ((this.mUIShowPassButtonWindow == null))
                {
                    this.mUIShowPassButtonWindow = new UIShowPassButtonWindow(this);
                }
                return this.mUIShowPassButtonWindow;
            }
        }
        
        public UIMainMenuStripMenuMenuBar UIMainMenuStripMenuMenuBar
        {
            get
            {
                if ((this.mUIMainMenuStripMenuMenuBar == null))
                {
                    this.mUIMainMenuStripMenuMenuBar = new UIMainMenuStripMenuMenuBar(this);
                }
                return this.mUIMainMenuStripMenuMenuBar;
            }
        }
        
        public UIStopHostspotWindow UIStopHostspotWindow
        {
            get
            {
                if ((this.mUIStopHostspotWindow == null))
                {
                    this.mUIStopHostspotWindow = new UIStopHostspotWindow(this);
                }
                return this.mUIStopHostspotWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIPortableHotspotWindoTitleBar mUIPortableHotspotWindoTitleBar;
        
        private UIStartHotspotWindow mUIStartHotspotWindow;
        
        private UIShowPassButtonWindow mUIShowPassButtonWindow;
        
        private UIMainMenuStripMenuMenuBar mUIMainMenuStripMenuMenuBar;
        
        private UIStopHostspotWindow mUIStopHostspotWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIPortableHotspotWindoTitleBar : WinTitleBar
    {
        
        public UIPortableHotspotWindoTitleBar(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.WindowTitles.Add("Portable Hotspot Windows");
            #endregion
        }
        
        #region Properties
        public WinButton UIMinimizeButton
        {
            get
            {
                if ((this.mUIMinimizeButton == null))
                {
                    this.mUIMinimizeButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIMinimizeButton.SearchProperties[WinButton.PropertyNames.Name] = "Minimize";
                    this.mUIMinimizeButton.WindowTitles.Add("Portable Hotspot Windows");
                    #endregion
                }
                return this.mUIMinimizeButton;
            }
        }
        
        public WinButton UICloseButton
        {
            get
            {
                if ((this.mUICloseButton == null))
                {
                    this.mUICloseButton = new WinButton(this);
                    #region Search Criteria
                    this.mUICloseButton.SearchProperties[WinButton.PropertyNames.Name] = "Close";
                    this.mUICloseButton.WindowTitles.Add("Portable Hotspot Windows");
                    #endregion
                }
                return this.mUICloseButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIMinimizeButton;
        
        private WinButton mUICloseButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIStartHotspotWindow : WinWindow
    {
        
        public UIStartHotspotWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "StartStopButton";
            this.WindowTitles.Add("Portable Hotspot Windows");
            #endregion
        }
        
        #region Properties
        public WinButton UIStartHotspotButton
        {
            get
            {
                if ((this.mUIStartHotspotButton == null))
                {
                    this.mUIStartHotspotButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIStartHotspotButton.SearchProperties[WinButton.PropertyNames.Name] = "Start Hotspot";
                    this.mUIStartHotspotButton.WindowTitles.Add("Portable Hotspot Windows");
                    #endregion
                }
                return this.mUIStartHotspotButton;
            }
        }
        
        public WinButton UIStopHostspotButton
        {
            get
            {
                if ((this.mUIStopHostspotButton == null))
                {
                    this.mUIStopHostspotButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIStopHostspotButton.SearchProperties[WinButton.PropertyNames.Name] = "Stop Hostspot";
                    this.mUIStopHostspotButton.WindowTitles.Add("Portable Hotspot Windows");
                    #endregion
                }
                return this.mUIStopHostspotButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIStartHotspotButton;
        
        private WinButton mUIStopHostspotButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIShowPassButtonWindow : WinWindow
    {
        
        public UIShowPassButtonWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "ShowPassButton";
            this.WindowTitles.Add("Portable Hotspot Windows");
            #endregion
        }
        
        #region Properties
        public WinButton UIShowPassButtonButton
        {
            get
            {
                if ((this.mUIShowPassButtonButton == null))
                {
                    this.mUIShowPassButtonButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIShowPassButtonButton.WindowTitles.Add("Portable Hotspot Windows");
                    #endregion
                }
                return this.mUIShowPassButtonButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIShowPassButtonButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIMainMenuStripMenuMenuBar : WinMenuBar
    {
        
        public UIMainMenuStripMenuMenuBar(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.WindowTitles.Add("Portable Hotspot Windows");
            #endregion
        }
        
        #region Properties
        public WinMenuItem UIAboutMenuItem
        {
            get
            {
                if ((this.mUIAboutMenuItem == null))
                {
                    this.mUIAboutMenuItem = new WinMenuItem(this);
                    #region Search Criteria
                    this.mUIAboutMenuItem.SearchProperties[WinMenuItem.PropertyNames.Name] = "About";
                    this.mUIAboutMenuItem.WindowTitles.Add("Portable Hotspot Windows");
                    #endregion
                }
                return this.mUIAboutMenuItem;
            }
        }
        
        public WinMenuItem UIExitMenuItem
        {
            get
            {
                if ((this.mUIExitMenuItem == null))
                {
                    this.mUIExitMenuItem = new WinMenuItem(this);
                    #region Search Criteria
                    this.mUIExitMenuItem.SearchProperties[WinMenuItem.PropertyNames.Name] = "Exit";
                    this.mUIExitMenuItem.WindowTitles.Add("Portable Hotspot Windows");
                    #endregion
                }
                return this.mUIExitMenuItem;
            }
        }
        
        public WinMenuItem UISetNetworkMenuItem
        {
            get
            {
                if ((this.mUISetNetworkMenuItem == null))
                {
                    this.mUISetNetworkMenuItem = new WinMenuItem(this);
                    #region Search Criteria
                    this.mUISetNetworkMenuItem.SearchProperties[WinMenuItem.PropertyNames.Name] = "Set Network";
                    this.mUISetNetworkMenuItem.WindowTitles.Add("Portable Hotspot Windows");
                    #endregion
                }
                return this.mUISetNetworkMenuItem;
            }
        }
        #endregion
        
        #region Fields
        private WinMenuItem mUIAboutMenuItem;
        
        private WinMenuItem mUIExitMenuItem;
        
        private WinMenuItem mUISetNetworkMenuItem;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIStopHostspotWindow : WinWindow
    {
        
        public UIStopHostspotWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "StartStopButton";
            this.WindowTitles.Add("Portable Hotspot Windows");
            #endregion
        }
        
        #region Properties
        public WinButton UIStopHostspotButton
        {
            get
            {
                if ((this.mUIStopHostspotButton == null))
                {
                    this.mUIStopHostspotButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIStopHostspotButton.SearchProperties[WinButton.PropertyNames.Name] = "Stop Hostspot";
                    this.mUIStopHostspotButton.WindowTitles.Add("Portable Hotspot Windows");
                    #endregion
                }
                return this.mUIStopHostspotButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIStopHostspotButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIAboutWindow : WinWindow
    {
        
        public UIAboutWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "About";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("About");
            #endregion
        }
        
        #region Properties
        public UICloseWindow UICloseWindow
        {
            get
            {
                if ((this.mUICloseWindow == null))
                {
                    this.mUICloseWindow = new UICloseWindow(this);
                }
                return this.mUICloseWindow;
            }
        }
        #endregion
        
        #region Fields
        private UICloseWindow mUICloseWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UICloseWindow : WinWindow
    {
        
        public UICloseWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "CloseButton";
            this.WindowTitles.Add("About");
            #endregion
        }
        
        #region Properties
        public WinButton UICloseButton
        {
            get
            {
                if ((this.mUICloseButton == null))
                {
                    this.mUICloseButton = new WinButton(this);
                    #region Search Criteria
                    this.mUICloseButton.SearchProperties[WinButton.PropertyNames.Name] = "Close";
                    this.mUICloseButton.WindowTitles.Add("About");
                    #endregion
                }
                return this.mUICloseButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUICloseButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIInformationWindow : WinWindow
    {
        
        public UIInformationWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Information";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "#32770";
            this.WindowTitles.Add("Information");
            #endregion
        }
        
        #region Properties
        public UIYesWindow UIYesWindow
        {
            get
            {
                if ((this.mUIYesWindow == null))
                {
                    this.mUIYesWindow = new UIYesWindow(this);
                }
                return this.mUIYesWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIYesWindow mUIYesWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIYesWindow : WinWindow
    {
        
        public UIYesWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "6";
            this.WindowTitles.Add("Information");
            #endregion
        }
        
        #region Properties
        public WinButton UIYesButton
        {
            get
            {
                if ((this.mUIYesButton == null))
                {
                    this.mUIYesButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIYesButton.SearchProperties[WinButton.PropertyNames.Name] = "Yes";
                    this.mUIYesButton.WindowTitles.Add("Information");
                    #endregion
                }
                return this.mUIYesButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIYesButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UISetHotspotWindow : WinWindow
    {
        
        public UISetHotspotWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Set Hotspot";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Set Hotspot");
            #endregion
        }
        
        #region Properties
        public UISSIDTextBoxWindow UISSIDTextBoxWindow
        {
            get
            {
                if ((this.mUISSIDTextBoxWindow == null))
                {
                    this.mUISSIDTextBoxWindow = new UISSIDTextBoxWindow(this);
                }
                return this.mUISSIDTextBoxWindow;
            }
        }
        
        public UIKeyTextBoxWindow UIKeyTextBoxWindow
        {
            get
            {
                if ((this.mUIKeyTextBoxWindow == null))
                {
                    this.mUIKeyTextBoxWindow = new UIKeyTextBoxWindow(this);
                }
                return this.mUIKeyTextBoxWindow;
            }
        }
        
        public UIShowPassButtonWindow1 UIShowPassButtonWindow
        {
            get
            {
                if ((this.mUIShowPassButtonWindow == null))
                {
                    this.mUIShowPassButtonWindow = new UIShowPassButtonWindow1(this);
                }
                return this.mUIShowPassButtonWindow;
            }
        }
        
        public UISetWindow UISetWindow
        {
            get
            {
                if ((this.mUISetWindow == null))
                {
                    this.mUISetWindow = new UISetWindow(this);
                }
                return this.mUISetWindow;
            }
        }
        
        public UIFromNetworkListComboWindow UIFromNetworkListComboWindow
        {
            get
            {
                if ((this.mUIFromNetworkListComboWindow == null))
                {
                    this.mUIFromNetworkListComboWindow = new UIFromNetworkListComboWindow(this);
                }
                return this.mUIFromNetworkListComboWindow;
            }
        }
        
        public UIToNetworkListComboBoWindow UIToNetworkListComboBoWindow
        {
            get
            {
                if ((this.mUIToNetworkListComboBoWindow == null))
                {
                    this.mUIToNetworkListComboBoWindow = new UIToNetworkListComboBoWindow(this);
                }
                return this.mUIToNetworkListComboBoWindow;
            }
        }
        
        public UIShareInternetWindow UIShareInternetWindow
        {
            get
            {
                if ((this.mUIShareInternetWindow == null))
                {
                    this.mUIShareInternetWindow = new UIShareInternetWindow(this);
                }
                return this.mUIShareInternetWindow;
            }
        }
        
        public UISetHotspotTitleBar UISetHotspotTitleBar
        {
            get
            {
                if ((this.mUISetHotspotTitleBar == null))
                {
                    this.mUISetHotspotTitleBar = new UISetHotspotTitleBar(this);
                }
                return this.mUISetHotspotTitleBar;
            }
        }
        #endregion
        
        #region Fields
        private UISSIDTextBoxWindow mUISSIDTextBoxWindow;
        
        private UIKeyTextBoxWindow mUIKeyTextBoxWindow;
        
        private UIShowPassButtonWindow1 mUIShowPassButtonWindow;
        
        private UISetWindow mUISetWindow;
        
        private UIFromNetworkListComboWindow mUIFromNetworkListComboWindow;
        
        private UIToNetworkListComboBoWindow mUIToNetworkListComboBoWindow;
        
        private UIShareInternetWindow mUIShareInternetWindow;
        
        private UISetHotspotTitleBar mUISetHotspotTitleBar;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UISSIDTextBoxWindow : WinWindow
    {
        
        public UISSIDTextBoxWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "SSIDTextBox";
            this.WindowTitles.Add("Set Hotspot");
            #endregion
        }
        
        #region Properties
        public WinEdit UISSIDTextBoxEdit
        {
            get
            {
                if ((this.mUISSIDTextBoxEdit == null))
                {
                    this.mUISSIDTextBoxEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUISSIDTextBoxEdit.WindowTitles.Add("Set Hotspot");
                    #endregion
                }
                return this.mUISSIDTextBoxEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUISSIDTextBoxEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIKeyTextBoxWindow : WinWindow
    {
        
        public UIKeyTextBoxWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "KeyTextBox";
            this.WindowTitles.Add("Set Hotspot");
            #endregion
        }
        
        #region Properties
        public WinEdit UIKeyTextBoxEdit
        {
            get
            {
                if ((this.mUIKeyTextBoxEdit == null))
                {
                    this.mUIKeyTextBoxEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIKeyTextBoxEdit.WindowTitles.Add("Set Hotspot");
                    #endregion
                }
                return this.mUIKeyTextBoxEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIKeyTextBoxEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIShowPassButtonWindow1 : WinWindow
    {
        
        public UIShowPassButtonWindow1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "ShowPassButton";
            this.WindowTitles.Add("Set Hotspot");
            #endregion
        }
        
        #region Properties
        public WinButton UITOButton
        {
            get
            {
                if ((this.mUITOButton == null))
                {
                    this.mUITOButton = new WinButton(this);
                    #region Search Criteria
                    this.mUITOButton.SearchProperties[WinButton.PropertyNames.Name] = "To";
                    this.mUITOButton.WindowTitles.Add("Set Hotspot");
                    #endregion
                }
                return this.mUITOButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUITOButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UISetWindow : WinWindow
    {
        
        public UISetWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "SetButton";
            this.WindowTitles.Add("Set Hotspot");
            #endregion
        }
        
        #region Properties
        public WinButton UISetButton
        {
            get
            {
                if ((this.mUISetButton == null))
                {
                    this.mUISetButton = new WinButton(this);
                    #region Search Criteria
                    this.mUISetButton.SearchProperties[WinButton.PropertyNames.Name] = "Set";
                    this.mUISetButton.WindowTitles.Add("Set Hotspot");
                    #endregion
                }
                return this.mUISetButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUISetButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIFromNetworkListComboWindow : WinWindow
    {
        
        public UIFromNetworkListComboWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "FromNetworkListComboBox";
            this.WindowTitles.Add("Set Hotspot");
            #endregion
        }
        
        #region Properties
        public WinButton UIOpenButton
        {
            get
            {
                if ((this.mUIOpenButton == null))
                {
                    this.mUIOpenButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIOpenButton.SearchProperties[WinButton.PropertyNames.Name] = "Open";
                    this.mUIOpenButton.WindowTitles.Add("Set Hotspot");
                    #endregion
                }
                return this.mUIOpenButton;
            }
        }
        
        public WinComboBox UIFromNetworkListComboComboBox
        {
            get
            {
                if ((this.mUIFromNetworkListComboComboBox == null))
                {
                    this.mUIFromNetworkListComboComboBox = new WinComboBox(this);
                    #region Search Criteria
                    this.mUIFromNetworkListComboComboBox.WindowTitles.Add("Set Hotspot");
                    #endregion
                }
                return this.mUIFromNetworkListComboComboBox;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIOpenButton;
        
        private WinComboBox mUIFromNetworkListComboComboBox;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIToNetworkListComboBoWindow : WinWindow
    {
        
        public UIToNetworkListComboBoWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "ToNetworkListComboBox";
            this.WindowTitles.Add("Set Hotspot");
            #endregion
        }
        
        #region Properties
        public WinButton UIOpenButton
        {
            get
            {
                if ((this.mUIOpenButton == null))
                {
                    this.mUIOpenButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIOpenButton.SearchProperties[WinButton.PropertyNames.Name] = "Open";
                    this.mUIOpenButton.WindowTitles.Add("Set Hotspot");
                    #endregion
                }
                return this.mUIOpenButton;
            }
        }
        
        public WinComboBox UIToNetworkListComboBoComboBox
        {
            get
            {
                if ((this.mUIToNetworkListComboBoComboBox == null))
                {
                    this.mUIToNetworkListComboBoComboBox = new WinComboBox(this);
                    #region Search Criteria
                    this.mUIToNetworkListComboBoComboBox.WindowTitles.Add("Set Hotspot");
                    #endregion
                }
                return this.mUIToNetworkListComboBoComboBox;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIOpenButton;
        
        private WinComboBox mUIToNetworkListComboBoComboBox;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIShareInternetWindow : WinWindow
    {
        
        public UIShareInternetWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "ShareInternetButton";
            this.WindowTitles.Add("Set Hotspot");
            #endregion
        }
        
        #region Properties
        public WinButton UIShareInternetButton
        {
            get
            {
                if ((this.mUIShareInternetButton == null))
                {
                    this.mUIShareInternetButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIShareInternetButton.SearchProperties[WinButton.PropertyNames.Name] = "Share Internet ";
                    this.mUIShareInternetButton.WindowTitles.Add("Set Hotspot");
                    #endregion
                }
                return this.mUIShareInternetButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIShareInternetButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UISetHotspotTitleBar : WinTitleBar
    {
        
        public UISetHotspotTitleBar(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.WindowTitles.Add("Set Hotspot");
            #endregion
        }
        
        #region Properties
        public WinButton UICloseButton
        {
            get
            {
                if ((this.mUICloseButton == null))
                {
                    this.mUICloseButton = new WinButton(this);
                    #region Search Criteria
                    this.mUICloseButton.SearchProperties[WinButton.PropertyNames.Name] = "Close";
                    this.mUICloseButton.WindowTitles.Add("Set Hotspot");
                    #endregion
                }
                return this.mUICloseButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUICloseButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIUserPromotedNotificaWindow : WinWindow
    {
        
        public UIUserPromotedNotificaWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "User Promoted Notification Area";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "ToolbarWindow32";
            this.WindowTitles.Add("User Promoted Notification Area");
            #endregion
        }
        
        #region Properties
        public UIUserPromotedNotificaToolBar UIUserPromotedNotificaToolBar
        {
            get
            {
                if ((this.mUIUserPromotedNotificaToolBar == null))
                {
                    this.mUIUserPromotedNotificaToolBar = new UIUserPromotedNotificaToolBar(this);
                }
                return this.mUIUserPromotedNotificaToolBar;
            }
        }
        #endregion
        
        #region Fields
        private UIUserPromotedNotificaToolBar mUIUserPromotedNotificaToolBar;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIUserPromotedNotificaToolBar : WinToolBar
    {
        
        public UIUserPromotedNotificaToolBar(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinToolBar.PropertyNames.Name] = "User Promoted Notification Area";
            this.WindowTitles.Add("User Promoted Notification Area");
            #endregion
        }
        
        #region Properties
        public WinButton UIPortableHotspotWindoButton
        {
            get
            {
                if ((this.mUIPortableHotspotWindoButton == null))
                {
                    this.mUIPortableHotspotWindoButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIPortableHotspotWindoButton.SearchProperties[WinButton.PropertyNames.Name] = "Portable Hotspot Windows";
                    this.mUIPortableHotspotWindoButton.WindowTitles.Add("User Promoted Notification Area");
                    #endregion
                }
                return this.mUIPortableHotspotWindoButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIPortableHotspotWindoButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIPortableHotspotWindoWindow2 : WinWindow
    {
        
        public UIPortableHotspotWindoWindow2()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "PortableHotspotWindows (Running) - Microsoft Visual Studio (Administrator)";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "HwndWrapper", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("PortableHotspotWindows (Running) - Microsoft Visual Studio (Administrator)");
            #endregion
        }
        
        #region Properties
        public UIDiagnosticToolsPane UIDiagnosticToolsPane
        {
            get
            {
                if ((this.mUIDiagnosticToolsPane == null))
                {
                    this.mUIDiagnosticToolsPane = new UIDiagnosticToolsPane(this);
                }
                return this.mUIDiagnosticToolsPane;
            }
        }
        #endregion
        
        #region Fields
        private UIDiagnosticToolsPane mUIDiagnosticToolsPane;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIDiagnosticToolsPane : WpfPane
    {
        
        public UIDiagnosticToolsPane(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfPane.PropertyNames.ClassName] = "Uia.ViewPresenter";
            this.SearchProperties[WpfPane.PropertyNames.AutomationId] = "ST:0:0:{6d4078d1-5951-4ed1-ac0e-0a8099c1cce5}";
            #endregion
        }
        
        #region Properties
        public UIItemPane UIItemPane
        {
            get
            {
                if ((this.mUIItemPane == null))
                {
                    this.mUIItemPane = new UIItemPane(this);
                }
                return this.mUIItemPane;
            }
        }
        #endregion
        
        #region Fields
        private UIItemPane mUIItemPane;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIItemPane : WpfPane
    {
        
        public UIItemPane(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfPane.PropertyNames.ClassName] = "Uia.HwndHost";
            #endregion
        }
        
        #region Properties
        public UISystemResourceNotifyClient UISystemResourceNotifyClient
        {
            get
            {
                if ((this.mUISystemResourceNotifyClient == null))
                {
                    this.mUISystemResourceNotifyClient = new UISystemResourceNotifyClient(this);
                }
                return this.mUISystemResourceNotifyClient;
            }
        }
        #endregion
        
        #region Fields
        private UISystemResourceNotifyClient mUISystemResourceNotifyClient;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UISystemResourceNotifyClient : WinClient
    {
        
        public UISystemResourceNotifyClient(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinControl.PropertyNames.Name] = "SystemResourceNotifyWindow";
            #endregion
        }
        
        #region Properties
        public UIDiagnosticToolsWindow UIDiagnosticToolsWindow
        {
            get
            {
                if ((this.mUIDiagnosticToolsWindow == null))
                {
                    this.mUIDiagnosticToolsWindow = new UIDiagnosticToolsWindow(this);
                }
                return this.mUIDiagnosticToolsWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIDiagnosticToolsWindow mUIDiagnosticToolsWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIDiagnosticToolsWindow : WinWindow
    {
        
        public UIDiagnosticToolsWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Diagnostic Tools";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "GenericPane";
            #endregion
        }
        
        #region Properties
        public UIItemCustom UIItemCustom
        {
            get
            {
                if ((this.mUIItemCustom == null))
                {
                    this.mUIItemCustom = new UIItemCustom(this);
                }
                return this.mUIItemCustom;
            }
        }
        #endregion
        
        #region Fields
        private UIItemCustom mUIItemCustom;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIItemCustom : WpfCustom
    {
        
        public UIItemCustom(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfControl.PropertyNames.ClassName] = "Uia.DocumentBaseView";
            #endregion
        }
        
        #region Properties
        public UIDiagnosticToolsCustom UIDiagnosticToolsCustom
        {
            get
            {
                if ((this.mUIDiagnosticToolsCustom == null))
                {
                    this.mUIDiagnosticToolsCustom = new UIDiagnosticToolsCustom(this);
                }
                return this.mUIDiagnosticToolsCustom;
            }
        }
        #endregion
        
        #region Fields
        private UIDiagnosticToolsCustom mUIDiagnosticToolsCustom;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIDiagnosticToolsCustom : WpfCustom
    {
        
        public UIDiagnosticToolsCustom(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfControl.PropertyNames.ClassName] = "Uia.PerformanceDebuggerDocumentView";
            this.SearchProperties[WpfControl.PropertyNames.Name] = "Diagnostic Tools";
            #endregion
        }
        
        #region Properties
        public UIItemPane1 UIItemPane
        {
            get
            {
                if ((this.mUIItemPane == null))
                {
                    this.mUIItemPane = new UIItemPane1(this);
                }
                return this.mUIItemPane;
            }
        }
        #endregion
        
        #region Fields
        private UIItemPane1 mUIItemPane;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIItemPane1 : WpfPane
    {
        
        public UIItemPane1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfPane.PropertyNames.ClassName] = "Uia.HwndHost";
            #endregion
        }
        
        #region Properties
        public UIItemClient UIItemClient
        {
            get
            {
                if ((this.mUIItemClient == null))
                {
                    this.mUIItemClient = new UIItemClient(this);
                }
                return this.mUIItemClient;
            }
        }
        #endregion
        
        #region Fields
        private UIItemClient mUIItemClient;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIItemClient : WinClient
    {
        
        public UIItemClient(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinControl.PropertyNames.ClassName] = "Internet Explorer_Server";
            #endregion
        }
        
        #region Properties
        public UISwimlanesViewDocument UISwimlanesViewDocument
        {
            get
            {
                if ((this.mUISwimlanesViewDocument == null))
                {
                    this.mUISwimlanesViewDocument = new UISwimlanesViewDocument(this);
                }
                return this.mUISwimlanesViewDocument;
            }
        }
        #endregion
        
        #region Fields
        private UISwimlanesViewDocument mUISwimlanesViewDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UISwimlanesViewDocument : HtmlDocument
    {
        
        public UISwimlanesViewDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Swimlanes View";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "C:/Program%20Files%20(x86)/Microsoft%20Visual%20Studio%2014.0/Common7/IDE/CommonE" +
                "xtensions/Platform/DiagnosticsHub/WebViews/PerformanceDebuggerSwimLanesView.html" +
                "";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "file://C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\Common7\\IDE\\CommonExte" +
                "nsions\\Platform\\DiagnosticsHub\\WebViews\\PerformanceDebuggerSwimLanesView.html";
            this.WindowTitles.Add("PortableHotspotWindows (Running) - Microsoft Visual Studio (Administrator)");
            #endregion
        }
        
        #region Properties
        public UIMainSwimlaneContainePane UIMainSwimlaneContainePane
        {
            get
            {
                if ((this.mUIMainSwimlaneContainePane == null))
                {
                    this.mUIMainSwimlaneContainePane = new UIMainSwimlaneContainePane(this);
                }
                return this.mUIMainSwimlaneContainePane;
            }
        }
        
        public UIFooterPane UIFooterPane
        {
            get
            {
                if ((this.mUIFooterPane == null))
                {
                    this.mUIFooterPane = new UIFooterPane(this);
                }
                return this.mUIFooterPane;
            }
        }
        #endregion
        
        #region Fields
        private UIMainSwimlaneContainePane mUIMainSwimlaneContainePane;
        
        private UIFooterPane mUIFooterPane;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIMainSwimlaneContainePane : HtmlDiv
    {
        
        public UIMainSwimlaneContainePane(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDiv.PropertyNames.Id] = "mainSwimlaneContainer";
            this.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Events\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n";
            this.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.Class] = "main-swimlane-container";
            this.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"main-swimlane-container\" id=\"mainSwimlaneContainer\" style=\"margin-top: 72p" +
                "x; margin-bottom: 19px;\"";
            this.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "27";
            this.WindowTitles.Add("PortableHotspotWindows (Running) - Microsoft Visual Studio (Administrator)");
            #endregion
        }
        
        #region Properties
        public HtmlDiv UIItemPane
        {
            get
            {
                if ((this.mUIItemPane == null))
                {
                    this.mUIItemPane = new HtmlDiv(this);
                    #region Search Criteria
                    this.mUIItemPane.SearchProperties[HtmlDiv.PropertyNames.Id] = null;
                    this.mUIItemPane.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUIItemPane.FilterProperties[HtmlDiv.PropertyNames.InnerText] = null;
                    this.mUIItemPane.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUIItemPane.FilterProperties[HtmlDiv.PropertyNames.Class] = "graph-scale-left";
                    this.mUIItemPane.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"graph-scale-left\" style=\"width: 100%; height: 100%; border-right-width: 1p" +
                        "x;\"";
                    this.mUIItemPane.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "35";
                    this.mUIItemPane.WindowTitles.Add("PortableHotspotWindows (Running) - Microsoft Visual Studio (Administrator)");
                    #endregion
                }
                return this.mUIItemPane;
            }
        }
        
        public HtmlCustom UIItemCustom
        {
            get
            {
                if ((this.mUIItemCustom == null))
                {
                    this.mUIItemCustom = new HtmlCustom(this);
                    #region Search Criteria
                    this.mUIItemCustom.SearchProperties["TagName"] = "CANVAS";
                    this.mUIItemCustom.SearchProperties["Id"] = null;
                    this.mUIItemCustom.SearchProperties[UITestControl.PropertyNames.Name] = null;
                    this.mUIItemCustom.FilterProperties["Class"] = "graph-canvas";
                    this.mUIItemCustom.FilterProperties["ControlDefinition"] = "width=\"436\" height=\"68\" class=\"graph-can";
                    this.mUIItemCustom.FilterProperties["TagInstance"] = "2";
                    this.mUIItemCustom.WindowTitles.Add("PortableHotspotWindows (Running) - Microsoft Visual Studio (Administrator)");
                    #endregion
                }
                return this.mUIItemCustom;
            }
        }
        
        public HtmlCustom UIItemCustom1
        {
            get
            {
                if ((this.mUIItemCustom1 == null))
                {
                    this.mUIItemCustom1 = new HtmlCustom(this);
                    #region Search Criteria
                    this.mUIItemCustom1.SearchProperties["TagName"] = "CANVAS";
                    this.mUIItemCustom1.SearchProperties["Id"] = null;
                    this.mUIItemCustom1.SearchProperties[UITestControl.PropertyNames.Name] = null;
                    this.mUIItemCustom1.FilterProperties["Class"] = "graph-canvas";
                    this.mUIItemCustom1.FilterProperties["ControlDefinition"] = "width=\"436\" height=\"68\" class=\"graph-can";
                    this.mUIItemCustom1.FilterProperties["TagInstance"] = "4";
                    this.mUIItemCustom1.WindowTitles.Add("PortableHotspotWindows (Running) - Microsoft Visual Studio (Administrator)");
                    #endregion
                }
                return this.mUIItemCustom1;
            }
        }
        #endregion
        
        #region Fields
        private HtmlDiv mUIItemPane;
        
        private HtmlCustom mUIItemCustom;
        
        private HtmlCustom mUIItemCustom1;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIFooterPane : HtmlDiv
    {
        
        public UIFooterPane(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDiv.PropertyNames.Id] = "footer";
            this.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.InnerText] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.Class] = "footer-container";
            this.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"footer-container\" id=\"footer\" style=\"visibility: visible;\"";
            this.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "109";
            this.WindowTitles.Add("PortableHotspotWindows (Running) - Microsoft Visual Studio (Administrator)");
            #endregion
        }
        
        #region Properties
        public HtmlDiv UIItemPane
        {
            get
            {
                if ((this.mUIItemPane == null))
                {
                    this.mUIItemPane = new HtmlDiv(this);
                    #region Search Criteria
                    this.mUIItemPane.SearchProperties[HtmlDiv.PropertyNames.Id] = null;
                    this.mUIItemPane.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUIItemPane.FilterProperties[HtmlDiv.PropertyNames.InnerText] = null;
                    this.mUIItemPane.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUIItemPane.FilterProperties[HtmlDiv.PropertyNames.Class] = "scrollbar";
                    this.mUIItemPane.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"scrollbar\"";
                    this.mUIItemPane.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "110";
                    this.mUIItemPane.WindowTitles.Add("PortableHotspotWindows (Running) - Microsoft Visual Studio (Administrator)");
                    #endregion
                }
                return this.mUIItemPane;
            }
        }
        #endregion
        
        #region Fields
        private HtmlDiv mUIItemPane;
        #endregion
    }
}
